name: hello world workflow

on:
  push:
   branches:
     - main
  pull_request:
   branches: 
     - main
  workflow_dispatch

jobs:
 hello:
   run-on:ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: hello world
      run: echo ""Hello World"
      shell: bash

 goodbye:
   run-on: ubuntu-latest
   steps:
    -name: goodbye
     run: echo "goodbye world"
     shell: bash
   
